apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ibm-license-service
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: 'ibm-licensing'
  sources:
    - repoURL: "https://github.com/IBM/ibm-licensing-operator"
      targetRevision: "master"
      path: deploy/argo-cd/components/license-service/helm-cluster-scoped
    - repoURL: "https://github.com/IBM/ibm-licensing-operator"
      targetRevision: "master"
      path: deploy/argo-cd/components/license-service/helm
    - helm:
        valuesObject:
          watchNamespace: ibm-licensing,ibm-licensing-scanner
